import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./_components/header/Header";
import "react-toastify/dist/ReactToastify.css";
import ToastProvider from "../_componets/ToastProvider";
import { handleWhoami } from "@/lib/actions/auth-actions";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const result = await handleWhoami();

  // ✅ Don’t 404 the whole app. Just pass user if exists.
  const user = result?.success ? result.data : null;

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <Header user={user} children={undefined} />
        {children}
      </body>
    </html>
  );
}
